APPROACHES:
  # agent_planner:
  #   NAME: "agent_planner"
  #   FLAGS:
  #     explorer: "agent"
  #     demonstrator: "oracle_process_planning"
  #     terminate_on_goal_reached_and_option_terminated: True
  #     agent_sdk_use_local_sandbox: True
  #     option_model_terminate_on_repeat: False
  #     agent_sdk_max_agent_turns_per_iteration: 50
  #     agent_planner_use_scratchpad: False
  #     agent_planner_use_visualize_state: True
  #     agent_planner_use_annotate_scene: True
  #     option_model_use_gui: True
  agent_bilevel:
    NAME: "agent_bilevel"
    FLAGS:
      explorer: "agent"
      demonstrator: "oracle_process_planning"
      terminate_on_goal_reached_and_option_terminated: True
      agent_sdk_use_local_sandbox: True
      option_model_terminate_on_repeat: False
      agent_sdk_max_agent_turns_per_iteration: 50
      agent_planner_use_scratchpad: False
      agent_planner_use_visualize_state: True
      agent_planner_use_annotate_scene: True
      option_model_use_gui: True
      agent_bilevel_log_state: False
  # agent_option_learning:
  #   NAME: "agent_option_learning"
  #   FLAGS:
  #     explorer: "agent"
  #     option_learner: "agent"
  #     demonstrator: "oracle_process_planning"
  #     terminate_on_goal_reached_and_option_terminated: True
  #     agent_sdk_use_local_sandbox: True
  #     agent_sdk_max_agent_turns_per_iteration: 50
