# Composed config: oracle approach
# Usage: python scripts/local/launch_simp.py -c predicatorv3/oracle.yaml
---
includes:
  - common.yaml
  - envs/all.yaml
APPROACHES:
  oracle:
    NAME: "oracle_process_planning"
    FLAGS:
      demonstrator: "oracle_process_planning"
      terminate_on_goal_reached_and_option_terminated: True
      bilevel_plan_without_sim: True
  # human_interaction:
  #   NAME: "human_interaction"
  #   FLAGS:
  #     human_interaction_approach_use_scripted_option: True
  #     human_interaction_approach_use_all_options: True
  #     scripted_option_dir: "scripted_option_policies"
  #     skill_phase_use_motion_planning: True
  #     terminate_on_goal_reached_and_option_terminated: True
